// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ergrujmelimnaifgxiup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyZ3J1am1lbGltbmFpZmd4aXVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTI5NDksImV4cCI6MjA2OTU2ODk0OX0.wJMxwv5YIbULCTZbAlwX59u07giL_hE54VPiavKu6AU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});